name: Bug Report
description: Create a report to help improve the plugin
title: "[Bug] "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: Thanks for taking the time to submit a bug report! Please fill out the fields below.
- type: input
  attributes:
    label: Plugin version
    placeholder: 1.6.4
  validations:
    required: true
- type: input
  attributes:
    label: Server software and version
    description: e.g. Spigot, Paper, Mohist, ...
    placeholder: Spigot 1.18.2
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: How do you trigger this bug? Please walk us through it step by step.
    placeholder: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: What is actually happening?
    description: Describe what is actually happening, i.e. what the bug is. Please add screenshots if applicable.
  validations:
    required: true
- type: textarea
  attributes:
    label: Relevant log output
    description: Please upload a log file or paste the relevant server log here.
- type: textarea
  attributes:
    label: Any additional comments?
    
